import assert from "node:assert/strict";
import test from "node:test";
import { AIPrivacyGateway } from "../src/ai-privacy-gateway.mjs";
import { PrivacyCapabilityAuthority } from "../src/capability-token.mjs";
import { ConsentAuthority } from "../src/consent-authority.mjs";
import { PrivacyDecisionPoint } from "../src/privacy-decision-point.mjs";
import { PrivacyEnforcementPoint } from "../src/privacy-enforcement-point.mjs";
import { PrivacyEvidenceLedger } from "../src/privacy-evidence.mjs";

function build(){ const consents=new ConsentAuthority(); consents.put({requester_id:"goreecloud.ai",resource_id:"drive:project-alpha",purpose:"answer-current-conversation",processing_zones:["local"],destinations:["goreecloud.ai"]}); const manifests=new Map([["goreecloud.ai",{resources:[{resource:"drive:project-alpha",purposes:["answer-current-conversation"],operations:["read"],processing_zones:["local"],destinations:["goreecloud.ai"]}]}]]); const pdp=new PrivacyDecisionPoint({manifests,consentAuthority:consents}); const pep=new PrivacyEnforcementPoint({decisionPoint:pdp,capabilityAuthority:new PrivacyCapabilityAuthority("0123456789abcdef0123456789abcdef"),evidenceLedger:new PrivacyEvidenceLedger()}); return new AIPrivacyGateway({enforcementPoint:pep}); }
function request(){return{request_id:"ai-1",requester:{id:"goreecloud.ai",type:"ai"},resource:{id:"drive:project-alpha",classification:"documents"},operation:"read",purpose:"answer-current-conversation",processing_zone:"local",destination:"goreecloud.ai",retention:{mode:"none"},external_disclosure:false};}

test("AI retrieval is scoped to approved model, zone and temporary single-use context",()=>{ const gateway=build(); const result=gateway.authorizeRetrieval({request:request(),model:{id:"ollama.local",processing_zone:"local",provider_type:"local"},conversation_id:"conversation-1",allowed_models:["ollama.local"]}); assert.ok(result.capability_token); assert.equal(result.context.no_training,true); assert.equal(gateway.consumeRetrieval(result.context.context_id).enforcement.authorized,true); assert.throws(()=>gateway.consumeRetrieval(result.context.context_id),/CAPABILITY_ALREADY_CONSUMED/); const disposed=gateway.disposeContext(result.context.context_id); assert.equal(disposed.disposed,true); assert.equal(disposed.capability_token,null); assert.ok(disposed.disposal_evidence_hash); assert.throws(()=>gateway.consumeRetrieval(result.context.context_id),/AI_CONTEXT_DISPOSED/); });

test("AI gateway rejects unapproved model or processing-zone expansion",()=>{ const gateway=build(); assert.throws(()=>gateway.authorizeRetrieval({request:request(),model:{id:"external.model",processing_zone:"local",provider_type:"approved_external"},conversation_id:"c",allowed_models:["ollama.local"]}),/AI_MODEL_NOT_AUTHORIZED/); assert.throws(()=>gateway.authorizeRetrieval({request:request(),model:{id:"ollama.local",processing_zone:"external",provider_type:"local"},conversation_id:"c",allowed_models:["ollama.local"]}),/AI_MODEL_PROCESSING_ZONE_MISMATCH/); });

test("RAG candidates are filtered before context by file folder classification and derived-data rules",()=>{ const gateway=build(); const result=gateway.authorizeRetrieval({request:request(),model:{id:"ollama.local",processing_zone:"local",provider_type:"local"},conversation_id:"conversation-1",allowed_models:["ollama.local"],retrieval_scope:{folder_ids:["folder-alpha"],classifications:["documents"]}}); const candidates=[{resource_id:"file-1",folder_id:"folder-alpha",classification:"documents",kind:"text",excerpt:"allowed"},{resource_id:"file-2",folder_id:"folder-beta",classification:"documents",kind:"text",excerpt:"wrong folder"},{resource_id:"file-3",folder_id:"folder-alpha",classification:"documents",kind:"embedding",excerpt:"embedding"},{resource_id:"file-4",folder_id:"folder-alpha",classification:"documents",kind:"text",derived:true,excerpt:"derived"}]; const filtered=gateway.filterCandidates(result.context.context_id,candidates,{conversation_id:"conversation-1"}); assert.deepEqual(filtered.map(item=>item.resource_id),["file-1"]); assert.throws(()=>gateway.filterCandidates(result.context.context_id,candidates,{conversation_id:"conversation-2"}),/AI_CONTEXT_CONVERSATION_MISMATCH/); });
